local StringBuilder = require "util.StringBuilder"

describe("util.StringBuilder", function()
  it("should construct without arguments", function()
    assert.are.equal("", tostring(StringBuilder()))
  end)
  it("should construct with one argument", function()
    assert.are.equal("hi", tostring(StringBuilder("hi")))
  end)
  it("should construct with multiple arguments", function()
    assert.are.equal("hi", tostring(StringBuilder("h","i")))
  end)
  it("should be able to append", function()
    assert.are.equal("hi", tostring(StringBuilder():append("hi")))
  end)
  it("should be able to append multiple values", function()
    assert.are.equal("hi", tostring(StringBuilder():append("h", "i")))
  end)
  it("should continue working after tostring", function()
    local s = StringBuilder()
    assert.are.equal("h", tostring(s:append("h")))
    assert.are.equal("hi", tostring(s:append("i")))
  end)
end)
